on:
  push: {branches: trunk}
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          hn-username: ${{ secrets.hn-username }}
          hn-password: ${{ secrets.hn-password }}
        run: |
          curl -L https://github.com/babashka/babashka/releases/download/v1.12.206/babashka-1.12.206-linux-amd64-static.tar.gz -o /tmp/bb.tar.gz
          tar xf /tmp/bb.tar.gz -C /tmp
          /tmp/bb onefeed.clj
          git config --global user.email "66850754+wingdeans@users.noreply.github.com"
          git config --global user.name "onefeed"
          git add -A
          git commit -m "Onefeed"
          git push
