on:
  push: {branches: trunk}
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: trunk
      - uses: actions/checkout@v4
        with:
          ref: publish
          path: publish
      - working-directory: publish
        env:
          HN_USERNAME: ${{ secrets.HN_USERNAME }}
          HN_PASSWORD: ${{ secrets.HN_PASSWORD }}
        run: |
          curl -L https://github.com/babashka/babashka/releases/download/v1.12.206/babashka-1.12.206-linux-amd64-static.tar.gz -o /tmp/bb.tar.gz
          tar xf /tmp/bb.tar.gz -C /tmp
          /tmp/bb ../trunk/onefeed.clj
          cp -r ../trunk/resources .
          git config --global user.email "66850754+wingdeans@users.noreply.github.com"
          git config --global user.name "onefeed"
          git add -A
          git commit -m "Onefeed"
          git push
      - uses: actions/upload-pages-artifact@v3
        with:
          path: publish
  deploy:
    needs: update
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4